dist: bionic
language: c
#sudo: false
branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
services:
  - docker


before_install:
  - docker pull ubuntu:bionic


#addons:
#  apt:
#    packages:
#    - texinfo
jobs:
  include:
  - stage: setup
    script:
    - pwd
    - ls ../
  - stage: build
    script:
    - docker run -w /code/gens -it --rm -v `pwd`/..:/code ubuntu:bionic /bin/bash -c "./build.sh"
      #- export PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig/
      #- dpkg-buildpackage -v $TRAVIS_TAG
  - stage: release to github
    script: 
    - echo "Deploying to github..."
    - docker run -w /code/gens -e TRAVIS_TAG:$TRAVIS_TAG -it --rm -v `pwd`/..:/code ubuntu:bionic /bin/bash -c "./build.sh"
    if: tag IS present
    deploy:
      provider: releases
      api_key: "$GITHUB_OAUTH_TOKEN"
      skip_cleanup: true
      file_glob: true
      file:
        - ../gens_*.deb
      on:
        tags: true
        repo: kubilus1/gens
